// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizApi.Data;

#nullable disable

namespace QuizApp.Migrations
{
    [DbContext(typeof(QuizAppDbContext))]
    [Migration("20260616061148_QuestionDate")]
    partial class QuestionDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizApi.Models.AnswerKeyExplanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerKeyExplanationHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("AnswerKeyExplanations");
                });

            modelBuilder.Entity("QuizApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GKUnitName")
                        .HasColumnType("integer");

                    b.Property<int>("MathsUnitName")
                        .HasColumnType("integer");

                    b.Property<Guid>("QnId")
                        .HasColumnType("uuid");

                    b.Property<int>("SclBookStandard")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<int>("TamilUnitName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QnId")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("QuizApi.Models.CorrectOption", b =>
                {
                    b.Property<Guid>("CorrectOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectOptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QnId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrectOptionId");

                    b.HasIndex("QnId")
                        .IsUnique();

                    b.ToTable("CorrectOption");
                });

            modelBuilder.Entity("QuizApi.Models.Option", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("OptionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("QuizApi.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectOptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("QuizApi.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSectionTest")
                        .HasColumnType("boolean");

                    b.Property<List<Guid>>("QnIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int?>("Section")
                        .HasColumnType("integer");

                    b.Property<string>("TestDescription")
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalTimeInMins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TestData");
                });

            modelBuilder.Entity("QuizApi.Models.AnswerKeyExplanation", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithOne("AnswerKeyExplanation")
                        .HasForeignKey("QuizApi.Models.AnswerKeyExplanation", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizApi.Models.Category", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithOne("QnCategory")
                        .HasForeignKey("QuizApi.Models.Category", "QnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizApi.Models.CorrectOption", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithOne("QnCorrectOption")
                        .HasForeignKey("QuizApi.Models.CorrectOption", "QnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizApi.Models.Option", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithMany("Options")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizApi.Models.Quiz", b =>
                {
                    b.Navigation("AnswerKeyExplanation");

                    b.Navigation("Options");

                    b.Navigation("QnCategory")
                        .IsRequired();

                    b.Navigation("QnCorrectOption")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
