// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApi.Data;

#nullable disable

namespace QuizApp.Migrations
{
    [DbContext(typeof(QuizAppDbContext))]
    partial class QuizAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GKUnitName")
                        .HasColumnType("int");

                    b.Property<int>("MathsUnitName")
                        .HasColumnType("int");

                    b.Property<Guid>("QnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SclBookStandard")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("TamilUnitName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QnId")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("QuizApi.Models.CorrectOption", b =>
                {
                    b.Property<Guid>("CorrectOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectOptionValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QnId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CorrectOptionId");

                    b.HasIndex("QnId")
                        .IsUnique();

                    b.ToTable("CorrectOption");
                });

            modelBuilder.Entity("QuizApi.Models.Option", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OptionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("QuizApi.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectOptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("QuizApi.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSectionTest")
                        .HasColumnType("bit");

                    b.Property<string>("QnIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.Property<string>("TestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalTimeInMins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TestData");
                });

            modelBuilder.Entity("QuizApi.Models.Category", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithOne("QnCategory")
                        .HasForeignKey("QuizApi.Models.Category", "QnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizApi.Models.CorrectOption", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithOne("QnCorrectOption")
                        .HasForeignKey("QuizApi.Models.CorrectOption", "QnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizApi.Models.Option", b =>
                {
                    b.HasOne("QuizApi.Models.Quiz", null)
                        .WithMany("Options")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizApi.Models.Quiz", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("QnCategory")
                        .IsRequired();

                    b.Navigation("QnCorrectOption")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
